#!/bin/bash

FILE=""
STRING=""
GTG=0

# check if arguments are valid
if [ -n "$1" ]
then
        if [ -n "$2" ]
        then
		FILE=$1
		STRING=$2
                if [ -f "$1" ]
                then
                    GTG=1
                else
		    # file does not exist
		    FILE=$1
		    touch ${FILE}
		    if [ $# -eq 0 ]
		    then
			    GTG=1
		    else
                        echo "Unable to create file ${FILE}"
                        exit 1
		    fi
                fi
        else
            echo "writestr parameter not specified"
            exit 1
        fi
else
        echo "writefile parameter not specified."
        exit 1
fi

# append the file with string data
if [ $GTG -eq 1 ]
then
	echo ${STRING} >> ${FILE}
fi
